version: "3.8"
services:
  database:
    image: mysql:8
    container_name: database
    command: --innodb-use-native-aio=0
    tty: true
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nestnet

  server:
    image: server
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: ${SERVER_HOST}
    entrypoint: bash ./docker/entrypoint.sh
    env_file: .env
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - database
    networks:
      - nestnet

  nginx:
    image: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${NGINX_HOST}
    env_file: .env
    ports:
      - ${NGINX_PORT}:80
    networks:
      - nestnet

networks:
  nestnet:
    driver: bridge
